#!/usr/bin/env node
// Reads compiled Foundry artifacts from ../contracts/out/<Name>.sol/<Name>.json
// and extracts just the `.abi` field into frontend/src/abis/<Name>.ts as a
// `const` array (typed with `as const` so wagmi/viem can infer argument and
// return types from the ABI itself).
//
// No external deps — plain Node (fs/path) so this script has zero install
// cost and can't drift from the rest of the toolchain.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// frontend/scripts -> frontend -> repo root -> contracts/out
const CONTRACTS_OUT = join(__dirname, "..", "..", "contracts", "out");
const ABIS_OUT_DIR = join(__dirname, "..", "src", "abis");

// frontend/scripts -> frontend -> repo root -> deployments/sepolia.json
const DEPLOYMENTS_SRC = join(__dirname, "..", "..", "deployments", "sepolia.json");
const DEPLOYMENTS_OUT = join(__dirname, "..", "src", "config", "deployments.sepolia.ts");

// Contract names required by the dapp (Passo 4.3).
const CONTRACTS = ["Pair", "Router", "Factory", "LendingPool", "MockOracle", "TestToken"];

function readAbi(name) {
  const artifactPath = join(CONTRACTS_OUT, `${name}.sol`, `${name}.json`);
  if (!existsSync(artifactPath)) {
    throw new Error(
      `Artifact not found for "${name}" at ${artifactPath}. ` +
        `Did you run "forge build" in ../contracts first?`,
    );
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Artifact ${artifactPath} has no "abi" array.`);
  }
  return artifact.abi;
}

function writeAbiModule(name, abi) {
  if (!existsSync(ABIS_OUT_DIR)) {
    mkdirSync(ABIS_OUT_DIR, { recursive: true });
  }
  const outPath = join(ABIS_OUT_DIR, `${name}.ts`);
  const banner =
    "// AUTO-GENERATED by `npm run gen:abis` — do not edit by hand.\n" +
    `// Source: contracts/out/${name}.sol/${name}.json (.abi field only)\n\n`;
  const body = `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(outPath, banner + body);
  return outPath;
}

function writeBarrelModule(names) {
  const lines = names.map((name) => `export { ${name}Abi } from "./${name}";`);
  const outPath = join(ABIS_OUT_DIR, "index.ts");
  const banner = "// AUTO-GENERATED by `npm run gen:abis` — do not edit by hand.\n\n";
  writeFileSync(outPath, banner + lines.join("\n") + "\n");
  return outPath;
}

function writeDeploymentsModule() {
  if (!existsSync(DEPLOYMENTS_SRC)) {
    throw new Error(
      `Deployments file not found at ${DEPLOYMENTS_SRC}. ` +
        `Expected ../deployments/sepolia.json relative to frontend/.`,
    );
  }
  const deployments = JSON.parse(readFileSync(DEPLOYMENTS_SRC, "utf8"));
  const configDir = dirname(DEPLOYMENTS_OUT);
  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }
  const banner =
    "// AUTO-GENERATED by `npm run gen:abis` — do not edit by hand.\n" +
    "// Source: ../deployments/sepolia.json\n\n";
  const body = `export const sepoliaDeployments = ${JSON.stringify(deployments, null, 2)} as const;\n`;
  writeFileSync(DEPLOYMENTS_OUT, banner + body);
  return DEPLOYMENTS_OUT;
}

function main() {
  const written = [];
  for (const name of CONTRACTS) {
    const abi = readAbi(name);
    written.push(writeAbiModule(name, abi));
  }
  written.push(writeBarrelModule(CONTRACTS));
  written.push(writeDeploymentsModule());

  console.log("Generated ABIs:");
  for (const path of written) {
    console.log(`  - ${path}`);
  }
}

main();
