// AUTO-GENERATED by `npm run gen:abis` — do not edit by hand.
// Source: ../deployments/sepolia.json

export const sepoliaDeployments = {
  "blockNumber": 11104173,
  "chainId": 11155111,
  "factory": "0x803B5d9EbA385383025ad07856B059201F202Fd0",
  "lendingPool": "0x14Bcb5Ebc00b4D023FB71B4BA60413FbcB24d31c",
  "mUSDC": "0x4CF16121615C0F4bBC94De15A9CcbaaBC9f623F4",
  "mWETH": "0xBE1A157e0dDEfA130E183bEFc6aE81BcCd1a9112",
  "oracle": "0xEf52E7129593C1b4531479780B8892C102526B60",
  "pair": "0xd3e6b9784A0edCE80451979dCF1457ABBd1B33b2",
  "router": "0x14E0ceAFd363e63CEEA412D1C47d57A0F8A963d6"
} as const;
